// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-app-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var APP_INFO = {
  name: "CyberGRC Command Center",
  description: "A Cybersecurity Governance, Risk & Compliance dashboard for security analysts, combining three hubs: Cyber Violations, Remediation, and Event Horizon (calendar).",
  hubs: [
    { id: "violations", name: "Cyber Violations Hub", path: "/violations", purpose: "Log, edit, close, and delete cybersecurity violations. Includes KPI donut charts and a searchable/filterable table." },
    { id: "remediation", name: "Remediation Hub", path: "/remediation", purpose: "Role-based workspace (GRC Analyst / Proponent) to track remediation items from a prior assessment, with metrics that filter the table by status and priority." },
    { id: "events", name: "Event Horizon Hub", path: "/events", purpose: "Multi-view calendar (dashboard, calendar grid, notes, tasks) for tracking cybersecurity activities. Supports drag-and-drop, ICS export, and category/priority filtering." }
  ],
  dataModels: {
    violation: ["id (uuid)", "number", "name", "description", "violatingUser", "status (open|closed)", "actionTaken (issue_violation|issue_warning|no_action)", "finalDecision", "grcComments"],
    remediationItem: ["id (REM-###)", "title", "description", "status (open|in_progress|pending_review|closed)", "priority (critical|high|medium|low)", "assignedToName", "dueDate", "category"],
    calendarEvent: ["id", "title", "category (meetings|audits|compliance|training)", "startDate", "endDate", "status", "priority"],
    task: ["id", "title", "completed", "priority", "dueDate"],
    note: ["id", "title", "content"]
  },
  note: "This app currently stores its GRC data in each browser's local storage (client-side only). MCP tools run server-side and cannot read per-browser state, so they expose app metadata and structure rather than live user data. To expose live data through MCP, the stores would need to be migrated to database tables."
};
var get_app_info_default = defineTool2({
  name: "get_app_info",
  title: "Get app info",
  description: "Return the CyberGRC app's name, description, hubs, routes, and data models. Use this first to understand what the app does.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(APP_INFO, null, 2) }],
    structuredContent: APP_INFO
  })
});

// src/lib/mcp/tools/list-hub-links.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var HUBS = {
  violations: { name: "Cyber Violations Hub", path: "/violations" },
  remediation: { name: "Remediation Hub", path: "/remediation" },
  events: { name: "Event Horizon Hub", path: "/events" },
  home: { name: "Home Dashboard", path: "/" }
};
var list_hub_links_default = defineTool3({
  name: "get_hub_link",
  title: "Get hub link",
  description: "Return the URL path for a specific hub in the CyberGRC app. Useful when guiding a user to a section.",
  inputSchema: {
    hub: z2.enum(["violations", "remediation", "events", "home"]).describe("Which hub to link to.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ hub }) => {
    const target = HUBS[hub];
    return {
      content: [{ type: "text", text: `${target.name}: ${target.path}` }],
      structuredContent: target
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cybergrc-mcp",
  title: "CyberGRC Command Center",
  version: "0.1.0",
  instructions: "Tools for the CyberGRC Command Center app. Call get_app_info first to learn what the app does, its three hubs (Violations, Remediation, Event Horizon), routes, and data models. Use get_hub_link to point users at a specific section. Use echo to verify connectivity. Live per-user data is not exposed through this MCP because the app currently stores it client-side.",
  tools: [get_app_info_default, list_hub_links_default, echo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
